resource_types:
- name: static-list-resource
  type: registry-image
  source:
    repository: taylorsilva/static-list-resource

resources:
- name: example-list
  type: static-list-resource
  source:
    list:
    - Kaladin
    - Shallan
    - Dalinar
    - Navani

- name: complex-list
  type: static-list-resource
  source:
    # list must always be of type string
    list:
    - |
      name: Kaladin
      type: windrunner
    - |
      name: Shallan
      type: lightweaver
    - |
      name: Dalinar
      type: bondsmith
    - |
      name: Navani
      type: bondsmith

jobs:
- name: list-job
  plan:
  - in_parallel:
    - get: example-list
    - get: complex-list
  - task: display-selected-items
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: alpine }
      inputs:
      - name: example-list
      - name: complex-list
      run:
        path: sh
        args:
        - -cx
        - |
          cat example-list/item
          cat complex-list/item
  - put: next-item
    resource: example-list
    params:
      previous: example-list/item
  - task: display-selected-item
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      inputs:
      - name: next-item
      run:
        path: cat
        args: ["next-item/item"]
  - put: next-item
    resource: complex-list
    params:
      previous: complex-list/item
